Repository IgniteUI/igniteui-wc-examples, pull requests merged in 2021-12, with the labels that each got.

#190 refactor(radio): update styling sample
  samples/inputs/radio/styling/src/index.css
Labels: area: docs, status: awaiting-test

#192 samples(input): added samples - vNext
  browser/public/index.html
  samples/inputs/input/helper-text/.prettierrc
  samples/inputs/input/helper-text/ReadMe.md
  samples/inputs/input/helper-text/index.html
  samples/inputs/input/helper-text/package.json
  samples/inputs/input/helper-text/sandbox.config.json
  samples/inputs/input/helper-text/src/index.css
  samples/inputs/input/helper-text/src/index.ts
  samples/inputs/input/helper-text/tsconfig.json
  samples/inputs/input/helper-text/webpack.config.js
  samples/inputs/input/overview/.prettierrc
  samples/inputs/input/overview/ReadMe.md
  samples/inputs/input/overview/index.html
  samples/inputs/input/overview/package.json
  samples/inputs/input/overview/sandbox.config.json
  samples/inputs/input/overview/src/index.css
  samples/inputs/input/overview/src/index.ts
  samples/inputs/input/overview/tsconfig.json
  samples/inputs/input/overview/webpack.config.js
  samples/inputs/input/prefix-suffix/.prettierrc
  samples/inputs/input/prefix-suffix/ReadMe.md
  samples/inputs/input/prefix-suffix/index.html
  samples/inputs/input/prefix-suffix/package.json
  samples/inputs/input/prefix-suffix/sandbox.config.json
  samples/inputs/input/prefix-suffix/src/index.css
  samples/inputs/input/prefix-suffix/src/index.ts
  samples/inputs/input/prefix-suffix/tsconfig.json
  samples/inputs/input/prefix-suffix/webpack.config.js
  samples/inputs/input/size/.prettierrc
  samples/inputs/input/size/ReadMe.md
  samples/inputs/input/size/index.html
  samples/inputs/input/size/package.json
  samples/inputs/input/size/sandbox.config.json
  samples/inputs/input/size/src/InputSizingStyle.css
  samples/inputs/input/size/src/index.css
  samples/inputs/input/size/src/index.ts
  samples/inputs/input/size/tsconfig.json
  samples/inputs/input/size/webpack.config.js
  samples/inputs/input/styling/.prettierrc
  samples/inputs/input/styling/ReadMe.md
  samples/inputs/input/styling/index.html
  samples/inputs/input/styling/package.json
  samples/inputs/input/styling/sandbox.config.json
  samples/inputs/input/styling/src/InputStyling.css
  samples/inputs/input/styling/src/index.css
  samples/inputs/input/styling/src/index.ts
  samples/inputs/input/styling/tsconfig.json
  samples/inputs/input/styling/webpack.config.js
Labels: area: browser

#193 fix date picker format length
  samples/editors/date-picker/format/index.html
Labels: status: in-review

#185 fix(dock-manager): add improvements for styling sample
  browser/package.json
  samples/layouts/dock-manager/styling/index.html
  samples/layouts/dock-manager/styling/package.json
  samples/layouts/dock-manager/styling/src/DockManagerStyles.css
  samples/layouts/dock-manager/styling/src/index.ts
  samples/layouts/dock-manager/styling/src/menu-component.ts
Labels: area: browser, status: awaiting-test

#195 fix(dm): change optional chaining
  samples/layouts/dock-manager/styling/src/index.ts
Labels: area: bug, status: verified

#199 mdd-update-filtering
  samples/grids/data-grid/column-filter-expressions/.prettierrc
  samples/grids/data-grid/column-filter-expressions/ReadMe.md
  samples/grids/data-grid/column-filter-expressions/index.html
  samples/grids/data-grid/column-filter-expressions/package.json
  samples/grids/data-grid/column-filter-expressions/sandbox.config.json
  samples/grids/data-grid/column-filter-expressions/src/DataGridSharedData.ts
  samples/grids/data-grid/column-filter-expressions/src/index.css
  samples/grids/data-grid/column-filter-expressions/src/index.ts
  samples/grids/data-grid/column-filter-expressions/tsconfig.json
  samples/grids/data-grid/column-filter-expressions/webpack.config.js
  samples/grids/data-grid/column-filtering/index.html
  samples/grids/data-grid/column-filtering/src/index.ts
Labels: status: in-review

#200 mdd-update-mcc
  samples/editors/multi-column-combobox/overview/package.json
  samples/editors/multi-column-combobox/overview/src/index.ts
Labels: status: in-review

#202 mdd-fix-operands
  browser/public/index.html
  samples/grids/data-grid/column-filter-operands/src/index.ts
Labels: status: in-review
