Repository IgniteUI/igniteui-wc-examples, pull requests merged in 2021-11, with the labels that each got.

#126 feat(checkbox): add checkbox component samples
  browser/public/index.html
  browser/src/router.ts
  browser/tasks/gulp-samples.js
  samples/inputs/checkbox/checked/.prettierrc
  samples/inputs/checkbox/checked/ReadMe.md
  samples/inputs/checkbox/checked/index.html
  samples/inputs/checkbox/checked/package.json
  samples/inputs/checkbox/checked/sandbox.config.json
  samples/inputs/checkbox/checked/src/index.css
  samples/inputs/checkbox/checked/src/index.ts
  samples/inputs/checkbox/checked/tsconfig.json
  samples/inputs/checkbox/checked/webpack.config.js
  samples/inputs/checkbox/disabled/.prettierrc
  samples/inputs/checkbox/disabled/ReadMe.md
  samples/inputs/checkbox/disabled/index.html
  samples/inputs/checkbox/disabled/package.json
  samples/inputs/checkbox/disabled/sandbox.config.json
  samples/inputs/checkbox/disabled/src/index.css
  samples/inputs/checkbox/disabled/src/index.ts
  samples/inputs/checkbox/disabled/tsconfig.json
  samples/inputs/checkbox/disabled/webpack.config.js
  samples/inputs/checkbox/indeterminate/.prettierrc
  samples/inputs/checkbox/indeterminate/ReadMe.md
  samples/inputs/checkbox/indeterminate/index.html
  samples/inputs/checkbox/indeterminate/package.json
  samples/inputs/checkbox/indeterminate/sandbox.config.json
  samples/inputs/checkbox/indeterminate/src/index.css
  samples/inputs/checkbox/indeterminate/src/index.ts
  samples/inputs/checkbox/indeterminate/tsconfig.json
  samples/inputs/checkbox/indeterminate/webpack.config.js
  samples/inputs/checkbox/label/.prettierrc
  samples/inputs/checkbox/label/ReadMe.md
  samples/inputs/checkbox/label/index.html
  samples/inputs/checkbox/label/package.json
  samples/inputs/checkbox/label/sandbox.config.json
  samples/inputs/checkbox/label/src/CheckboxLabelStyles.css
  samples/inputs/checkbox/label/src/index.css
  samples/inputs/checkbox/label/src/index.ts
  samples/inputs/checkbox/label/tsconfig.json
  samples/inputs/checkbox/label/webpack.config.js
  samples/inputs/checkbox/sample-1/.prettierrc
  samples/inputs/checkbox/sample-1/ReadMe.md
  samples/inputs/checkbox/sample-1/index.html
  samples/inputs/checkbox/sample-1/package.json
  samples/inputs/checkbox/sample-1/sandbox.config.json
  samples/inputs/checkbox/sample-1/src/index.css
  samples/inputs/checkbox/sample-1/src/index.ts
  samples/inputs/checkbox/sample-1/tsconfig.json
  samples/inputs/checkbox/sample-1/webpack.config.js
Labels: checkbox

#123 feat(switch): add switch component samples
  browser/public/index.html
  browser/src/router.ts
  browser/tasks/gulp-samples.js
  samples/inputs/switch/checked/.prettierrc
  samples/inputs/switch/checked/ReadMe.md
  samples/inputs/switch/checked/index.html
  samples/inputs/switch/checked/package.json
  samples/inputs/switch/checked/sandbox.config.json
  samples/inputs/switch/checked/src/index.css
  samples/inputs/switch/checked/src/index.ts
  samples/inputs/switch/checked/tsconfig.json
  samples/inputs/switch/checked/webpack.config.js
  samples/inputs/switch/disabled/.prettierrc
  samples/inputs/switch/disabled/ReadMe.md
  samples/inputs/switch/disabled/index.html
  samples/inputs/switch/disabled/package.json
  samples/inputs/switch/disabled/sandbox.config.json
  samples/inputs/switch/disabled/src/index.css
  samples/inputs/switch/disabled/src/index.ts
  samples/inputs/switch/disabled/tsconfig.json
  samples/inputs/switch/disabled/webpack.config.js
  samples/inputs/switch/label/.prettierrc
  samples/inputs/switch/label/ReadMe.md
  samples/inputs/switch/label/index.html
  samples/inputs/switch/label/package.json
  samples/inputs/switch/label/sandbox.config.json
  samples/inputs/switch/label/src/index.css
  samples/inputs/switch/label/src/index.ts
  samples/inputs/switch/label/tsconfig.json
  samples/inputs/switch/label/webpack.config.js
  samples/inputs/switch/sample-1/.prettierrc
  samples/inputs/switch/sample-1/ReadMe.md
  samples/inputs/switch/sample-1/index.html
  samples/inputs/switch/sample-1/package.json
  samples/inputs/switch/sample-1/sandbox.config.json
  samples/inputs/switch/sample-1/src/index.css
  samples/inputs/switch/sample-1/src/index.ts
  samples/inputs/switch/sample-1/tsconfig.json
  samples/inputs/switch/sample-1/webpack.config.js
Labels: switch

#122 feat(nav-drawer): add samples for navigation drawer
  browser/public/index.html
  browser/src/router.ts
  browser/tasks/gulp-samples.js
  samples/menus/nav-drawer/add-drawer-items/.prettierrc
  samples/menus/nav-drawer/add-drawer-items/ReadMe.md
  samples/menus/nav-drawer/add-drawer-items/index.html
  samples/menus/nav-drawer/add-drawer-items/package.json
  samples/menus/nav-drawer/add-drawer-items/sandbox.config.json
  samples/menus/nav-drawer/add-drawer-items/src/index.css
  samples/menus/nav-drawer/add-drawer-items/src/index.ts
  samples/menus/nav-drawer/add-drawer-items/tsconfig.json
  samples/menus/nav-drawer/add-drawer-items/webpack.config.js
  samples/menus/nav-drawer/add-mini/.prettierrc
  samples/menus/nav-drawer/add-mini/ReadMe.md
  samples/menus/nav-drawer/add-mini/index.html
  samples/menus/nav-drawer/add-mini/package.json
  samples/menus/nav-drawer/add-mini/sandbox.config.json
  samples/menus/nav-drawer/add-mini/src/index.css
  samples/menus/nav-drawer/add-mini/src/index.ts
  samples/menus/nav-drawer/add-mini/tsconfig.json
  samples/menus/nav-drawer/add-mini/webpack.config.js
  samples/menus/nav-drawer/add-positions-navbar/.prettierrc
  samples/menus/nav-drawer/add-positions-navbar/ReadMe.md
  samples/menus/nav-drawer/add-positions-navbar/index.html
  samples/menus/nav-drawer/add-positions-navbar/package.json
  samples/menus/nav-drawer/add-positions-navbar/sandbox.config.json
  samples/menus/nav-drawer/add-positions-navbar/src/index.css
  samples/menus/nav-drawer/add-positions-navbar/src/index.ts
  samples/menus/nav-drawer/add-positions-navbar/tsconfig.json
  samples/menus/nav-drawer/add-positions-navbar/webpack.config.js
  samples/menus/nav-drawer/styling/.prettierrc
  samples/menus/nav-drawer/styling/ReadMe.md
  samples/menus/nav-drawer/styling/index.html
  samples/menus/nav-drawer/styling/package.json
  samples/menus/nav-drawer/styling/sandbox.config.json
  samples/menus/nav-drawer/styling/src/drawer-styling.css
  samples/menus/nav-drawer/styling/src/index.css
  samples/menus/nav-drawer/styling/src/index.ts
  samples/menus/nav-drawer/styling/tsconfig.json
  samples/menus/nav-drawer/styling/webpack.config.js
Labels: area: browser

#109 feat(Card): Adding Card component samples
  browser/package.json
  browser/public/index.html
  browser/src/assets/media/ROZES-Under-the-Grave.jpg
  browser/src/assets/media/here_media.jpg
  browser/src/assets/media/mellow_d.jpg
  browser/src/index.ts
  browser/tasks/gulp-samples.js
  samples/layouts/card/horizontal/.prettierrc
  samples/layouts/card/horizontal/ReadMe.md
  samples/layouts/card/horizontal/index.html
  samples/layouts/card/horizontal/package.json
  samples/layouts/card/horizontal/sandbox.config.json
  samples/layouts/card/horizontal/src/CardHorizontal.css
  samples/layouts/card/horizontal/src/index.css
  samples/layouts/card/horizontal/src/index.ts
  samples/layouts/card/horizontal/tsconfig.json
  samples/layouts/card/horizontal/webpack.config.js
  samples/layouts/card/overview/.prettierrc
  samples/layouts/card/overview/ReadMe.md
  samples/layouts/card/overview/index.html
  samples/layouts/card/overview/package.json
  samples/layouts/card/overview/sandbox.config.json
  samples/layouts/card/overview/src/CardOverview.css
  samples/layouts/card/overview/src/index.css
  samples/layouts/card/overview/src/index.ts
  samples/layouts/card/overview/tsconfig.json
  samples/layouts/card/overview/webpack.config.js
  samples/layouts/card/semi-horizontal/.prettierrc
  samples/layouts/card/semi-horizontal/ReadMe.md
  samples/layouts/card/semi-horizontal/index.html
  samples/layouts/card/semi-horizontal/package.json
  samples/layouts/card/semi-horizontal/sandbox.config.json
  samples/layouts/card/semi-horizontal/src/SemiHorizontal.css
  samples/layouts/card/semi-horizontal/src/index.css
  samples/layouts/card/semi-horizontal/src/index.ts
  samples/layouts/card/semi-horizontal/tsconfig.json
  samples/layouts/card/semi-horizontal/webpack.config.js
  samples/layouts/card/styling/.prettierrc
  samples/layouts/card/styling/ReadMe.md
  samples/layouts/card/styling/index.html
  samples/layouts/card/styling/package.json
  samples/layouts/card/styling/sandbox.config.json
  samples/layouts/card/styling/src/CardStyling.css
  samples/layouts/card/styling/src/index.css
  samples/layouts/card/styling/src/index.ts
  samples/layouts/card/styling/tsconfig.json
  samples/layouts/card/styling/webpack.config.js
Labels: status: in-review

#124 feat(avatar): add avatar component samples
  browser/public/index.html
  samples/layouts/avatar/icon/index.html
  samples/layouts/avatar/icon/src/IconAvatarStyles.css
  samples/layouts/avatar/icon/src/index.css
  samples/layouts/avatar/icon/src/index.ts
  samples/layouts/avatar/image/index.html
  samples/layouts/avatar/image/men1.jpeg
  samples/layouts/avatar/image/src/ImageAvatarStyles.css
  samples/layouts/avatar/image/src/index.css
  samples/layouts/avatar/image/src/index.ts
  samples/layouts/avatar/initials/index.html
  samples/layouts/avatar/initials/src/InitialsAvatarStyles.css
  samples/layouts/avatar/initials/src/index.css
  samples/layouts/avatar/initials/src/index.ts
  samples/layouts/avatar/shape/index.html
  samples/layouts/avatar/shape/src/AvatarShapeStyles.css
  samples/layouts/avatar/shape/src/index.css
  samples/layouts/avatar/shape/src/index.ts
  samples/layouts/avatar/size/index.html
  samples/layouts/avatar/size/src/AvatarSizeStyles.css
  samples/layouts/avatar/size/src/index.css
  samples/layouts/avatar/size/src/index.ts
Labels: avatar

#107 feat(list): add samples for list web component #101
  browser/public/index.html
  browser/src/assets/avatar/1.jpg
  browser/src/assets/avatar/2.jpg
  browser/src/assets/avatar/3.jpg
  samples/grids/list/add-list-items/.prettierrc
  samples/grids/list/add-list-items/ReadMe.md
  samples/grids/list/add-list-items/index.html
  samples/grids/list/add-list-items/package.json
  samples/grids/list/add-list-items/sandbox.config.json
  samples/grids/list/add-list-items/src/index.css
  samples/grids/list/add-list-items/src/index.ts
  samples/grids/list/add-list-items/tsconfig.json
  samples/grids/list/add-list-items/webpack.config.js
  samples/grids/list/list-item-content/.prettierrc
  samples/grids/list/list-item-content/ReadMe.md
  samples/grids/list/list-item-content/index.html
  samples/grids/list/list-item-content/package.json
  samples/grids/list/list-item-content/sandbox.config.json
  samples/grids/list/list-item-content/src/index.css
  samples/grids/list/list-item-content/src/index.ts
  samples/grids/list/list-item-content/tsconfig.json
  samples/grids/list/list-item-content/webpack.config.js
  samples/grids/list/overview/.prettierrc
  samples/grids/list/overview/ReadMe.md
  samples/grids/list/overview/index.html
  samples/grids/list/overview/package.json
  samples/grids/list/overview/sandbox.config.json
  samples/grids/list/overview/src/index.css
  samples/grids/list/overview/src/index.ts
  samples/grids/list/overview/tsconfig.json
  samples/grids/list/overview/webpack.config.js
  samples/grids/list/styling/.prettierrc
  samples/grids/list/styling/ReadMe.md
  samples/grids/list/styling/index.html
  samples/grids/list/styling/package.json
  samples/grids/list/styling/sandbox.config.json
  samples/grids/list/styling/src/ListStyling.css
  samples/grids/list/styling/src/index.css
  samples/grids/list/styling/src/index.ts
  samples/grids/list/styling/tsconfig.json
  samples/grids/list/styling/webpack.config.js
Labels: area: browser

#108 sample(form): add sample and config - vNext
  browser/public/index.html
  browser/src/router.ts
  browser/tasks/gulp-samples.js
  samples/data/form/overview/.prettierrc
  samples/data/form/overview/ReadMe.md
  samples/data/form/overview/index.html
  samples/data/form/overview/package.json
  samples/data/form/overview/sandbox.config.json
  samples/data/form/overview/src/index.css
  samples/data/form/overview/src/index.ts
  samples/data/form/overview/tsconfig.json
  samples/data/form/overview/webpack.config.js
Labels: area: browser

#134 fix(form): fixed sample when loading in browser
  samples/inputs/form/overview/index.html
  samples/inputs/form/overview/src/index.ts
Labels: area: docs

#135 Fixed missing icons in card samples
  samples/layouts/card/overview/src/index.ts
  samples/layouts/card/styling/src/index.ts
Labels: status: resolved

#133 fix(avatar): samples incomplete implementation
  browser/public/index.html
  browser/src/assets/media/men1.jpeg
  samples/layouts/avatar/icon/.prettierrc
  samples/layouts/avatar/icon/ReadMe.md
  samples/layouts/avatar/icon/index.html
  samples/layouts/avatar/icon/package.json
  samples/layouts/avatar/icon/sandbox.config.json
  samples/layouts/avatar/icon/src/IconAvatarStyles.css
  samples/layouts/avatar/icon/src/index.ts
  samples/layouts/avatar/icon/tsconfig.json
  samples/layouts/avatar/icon/webpack.config.js
  samples/layouts/avatar/image/.prettierrc
  samples/layouts/avatar/image/ReadMe.md
  samples/layouts/avatar/image/index.html
  samples/layouts/avatar/image/package.json
  samples/layouts/avatar/image/sandbox.config.json
  samples/layouts/avatar/image/src/ImageAvatarStyles.css
  samples/layouts/avatar/image/src/index.ts
  samples/layouts/avatar/image/tsconfig.json
  samples/layouts/avatar/image/webpack.config.js
  samples/layouts/avatar/initials/.prettierrc
  samples/layouts/avatar/initials/ReadMe.md
  samples/layouts/avatar/initials/index.html
  samples/layouts/avatar/initials/package.json
  samples/layouts/avatar/initials/sandbox.config.json
  samples/layouts/avatar/initials/src/InitialsAvatarStyles.css
  samples/layouts/avatar/initials/src/index.ts
  samples/layouts/avatar/initials/tsconfig.json
  samples/layouts/avatar/initials/webpack.config.js
  samples/layouts/avatar/shape/.prettierrc
  samples/layouts/avatar/shape/ReadMe.md
  samples/layouts/avatar/shape/index.html
  samples/layouts/avatar/shape/package.json
  samples/layouts/avatar/shape/sandbox.config.json
  samples/layouts/avatar/shape/src/AvatarShapeStyles.css
  samples/layouts/avatar/shape/src/index.ts
  samples/layouts/avatar/shape/tsconfig.json
  samples/layouts/avatar/shape/webpack.config.js
  samples/layouts/avatar/size/.prettierrc
  samples/layouts/avatar/size/ReadMe.md
  samples/layouts/avatar/size/index.html
  samples/layouts/avatar/size/package.json
  samples/layouts/avatar/size/sandbox.config.json
  samples/layouts/avatar/size/src/AvatarSizeStyles.css
  samples/layouts/avatar/size/src/index.ts
  samples/layouts/avatar/size/tsconfig.json
  samples/layouts/avatar/size/webpack.config.js
Labels: avatar

#146 feat(samples): add ripple component samples
  browser/public/index.html
  browser/tasks/gulp-samples.js
  samples/inputs/ripple/button/.prettierrc
  samples/inputs/ripple/button/ReadMe.md
  samples/inputs/ripple/button/index.html
  samples/inputs/ripple/button/package.json
  samples/inputs/ripple/button/sandbox.config.json
  samples/inputs/ripple/button/src/index.css
  samples/inputs/ripple/button/src/index.ts
  samples/inputs/ripple/button/tsconfig.json
  samples/inputs/ripple/button/webpack.config.js
  samples/inputs/ripple/color/.prettierrc
  samples/inputs/ripple/color/ReadMe.md
  samples/inputs/ripple/color/index.html
  samples/inputs/ripple/color/package.json
  samples/inputs/ripple/color/sandbox.config.json
  samples/inputs/ripple/color/src/RippleColorStyles.css
  samples/inputs/ripple/color/src/index.css
  samples/inputs/ripple/color/src/index.ts
  samples/inputs/ripple/color/tsconfig.json
  samples/inputs/ripple/color/webpack.config.js
Labels: ripple

#149 sync mini and nav drawer items
  samples/menus/nav-drawer/add-mini/index.html
  samples/menus/nav-drawer/add-mini/package.json
  samples/menus/nav-drawer/add-mini/src/index.ts
Labels: control: navigation-drawer

#151 mdd-Revert&-UpdateTypescript
  browser/package.json
  browser/public/index.html
  browser/src/router.ts
  browser/tasks/gulp-samples.js
  browser/tsconfig.json
  browser/webpack.config.js
Labels: status: in-review

#160 samples(navbar): removed basic sample
  browser/public/index.html
  samples/menus/nav-bar/content/.prettierrc
  samples/menus/nav-bar/content/ReadMe.md
  samples/menus/nav-bar/content/index.html
  samples/menus/nav-bar/content/package.json
  samples/menus/nav-bar/content/sandbox.config.json
  samples/menus/nav-bar/content/src/index.css
  samples/menus/nav-bar/content/src/index.ts
  samples/menus/nav-bar/content/tsconfig.json
  samples/menus/nav-bar/content/webpack.config.js
  samples/menus/nav-bar/overview/index.html
  samples/menus/nav-bar/overview/package.json
  samples/menus/nav-bar/overview/src/index.ts
  samples/menus/nav-bar/styling/index.html
  samples/menus/nav-bar/styling/package.json
  samples/menus/nav-bar/styling/src/NavbarStyling.css
Labels: control: lob

#158 fix(lob): fix samples with incorrect layout
  samples/grids/list/add-list-items/index.html
  samples/grids/list/list-item-content/index.html
  samples/grids/list/overview/index.html
  samples/grids/list/styling/index.html
  samples/inputs/badge/outlined/index.html
  samples/inputs/badge/shape/index.html
  samples/inputs/badge/variants/index.html
  samples/inputs/button/contained/index.html
  samples/inputs/button/download/index.html
  samples/inputs/button/fab/index.html
  samples/inputs/button/flat/index.html
  samples/inputs/button/outlined/index.html
  samples/inputs/button/overview/index.html
  samples/inputs/button/size/index.html
  samples/inputs/button/styling/index.html
  samples/inputs/checkbox/checked/index.html
  samples/inputs/checkbox/disabled/index.html
  samples/inputs/checkbox/indeterminate/index.html
  samples/inputs/checkbox/label/index.html
  samples/inputs/checkbox/sample-1/index.html
  samples/inputs/switch/checked/index.html
  samples/inputs/switch/disabled/index.html
  samples/inputs/switch/label/index.html
  samples/inputs/switch/sample-1/index.html
  samples/layouts/avatar/icon/index.html
  samples/layouts/avatar/image/index.html
  samples/layouts/avatar/initials/index.html
  samples/layouts/avatar/shape/index.html
  samples/layouts/avatar/size/index.html
  samples/menus/nav-drawer/add-mini/index.html
  samples/menus/nav-drawer/add-mini/src/index.ts
  samples/menus/nav-drawer/add-positions-navbar/index.html
  samples/menus/nav-drawer/add-positions-navbar/src/index.ts
  samples/menus/nav-drawer/styling/index.html
Labels: control: lob

#159 set nav drawer active item on click
  samples/menus/nav-drawer/add-drawer-items/src/index.ts
  samples/menus/nav-drawer/add-positions-navbar/index.html
  samples/menus/nav-drawer/add-positions-navbar/src/index.ts
  samples/menus/nav-drawer/styling/src/index.ts
Labels: area: browser, control: navigation-drawer

#161 Fix some samples assets
  browser/src/assets/avatar/1.jpg
  browser/src/assets/avatar/2.jpg
  browser/src/assets/avatar/3.jpg
  browser/src/assets/media/ROZES-Under-the-Grave.jpg
  browser/src/assets/media/here_media.jpg
  browser/src/assets/media/mellow_d.jpg
  browser/src/assets/media/men1.jpeg
  samples/grids/list/overview/index.html
  samples/grids/list/styling/index.html
  samples/layouts/avatar/image/index.html
  samples/layouts/card/horizontal/index.html
  samples/layouts/card/semi-horizontal/index.html
Labels: status: resolved

#176 fix(badge): samples styling issue
  samples/inputs/badge/outlined/index.html
  samples/inputs/badge/shape/index.html
  samples/inputs/badge/variants/index.html
Labels: control: badge

#171 fix(button): set flat variant to buttons and change default size
  samples/inputs/button/flat/index.html
  samples/inputs/button/overview/index.html
  samples/inputs/button/size/index.html
  samples/inputs/button/styling/src/ButtonStyle.css
  samples/inputs/button/styling/src/index.ts
Labels: area: browser

#179 fix(navbar): defineComponents icon
  samples/menus/nav-bar/overview/src/index.ts
Labels: area: browser

#182 add container with margin on ripple samples
  samples/inputs/ripple/button/index.html
  samples/inputs/ripple/color/index.html
Labels: status: verified

#175 sample(form): remove novalidate
  samples/inputs/form/overview/index.html
Labels: area: browser, status: verified

#178 Increase button margin
  samples/menus/nav-drawer/add-mini/index.html
Labels: area: browser

#181 Add spacing between radio btns and component below and remove div from calendar samples
  samples/grids/list/overview/index.html
  samples/menus/nav-drawer/add-positions-navbar/index.html
  samples/scheduling/calendar/disabled-dates/index.html
  samples/scheduling/calendar/formatting/index.html
  samples/scheduling/calendar/header/index.html
  samples/scheduling/calendar/multiple-months/index.html
  samples/scheduling/calendar/multiple-selection/index.html
  samples/scheduling/calendar/overview/index.html
  samples/scheduling/calendar/range-selection/index.html
  samples/scheduling/calendar/size/index.html
  samples/scheduling/calendar/special-dates/index.html
  samples/scheduling/calendar/styling/index.html
  samples/scheduling/calendar/styling/webpack.config.js
  samples/scheduling/calendar/week-numbers/index.html
Labels: area: browser

#163 fix(dock-manager): add improvements for styling sample
  browser/src/assets/brands/aa.png
  browser/src/assets/brands/amazon.png
  browser/src/assets/brands/amc.png
  browser/src/assets/brands/apple.png
  browser/src/assets/brands/canoo.png
  browser/src/assets/brands/gme.png
  browser/src/assets/brands/google.png
  browser/src/assets/brands/lucid.png
  browser/src/assets/brands/maxar.png
  browser/src/assets/brands/meta.png
  browser/src/assets/brands/microsoft.png
  browser/src/assets/brands/netflix.png
  browser/src/assets/brands/nio.png
  browser/src/assets/brands/palantir.png
  browser/src/assets/brands/pfizer.png
  browser/src/assets/brands/roku.png
  browser/src/assets/brands/spce.jpg
  browser/src/assets/brands/stoneco.png
  browser/src/assets/brands/tesla.png
  samples/layouts/dock-manager/styling/index.html
  samples/layouts/dock-manager/styling/package.json
  samples/layouts/dock-manager/styling/src/DockManagerStyles.css
  samples/layouts/dock-manager/styling/src/index.ts
Labels: area: browser

#186 use registerIconFromText and remove extra loaders
  samples/inputs/icon-button/size/src/index.ts
  samples/inputs/icon-button/styling/src/index.ts
  samples/inputs/icon-button/variant/src/index.ts
  samples/layouts/avatar/icon/src/index.ts
  samples/layouts/avatar/image/src/index.ts
  samples/layouts/avatar/initials/src/index.ts
  samples/layouts/avatar/shape/src/index.ts
  samples/layouts/avatar/size/src/index.ts
  samples/layouts/icon/sizing/src/index.ts
  samples/layouts/icon/styling/src/index.ts
  samples/menus/nav-drawer/add-drawer-items/src/index.ts
  samples/menus/nav-drawer/add-mini/src/index.ts
  samples/menus/nav-drawer/add-positions-navbar/src/index.ts
  samples/menus/nav-drawer/styling/src/index.ts
  samples/scheduling/calendar/styling/webpack.config.js
Labels: area: browser, status: verified
