Repository IgniteUI/igniteui-wc-examples, pull requests merged in 2021-09, with the labels that each got.

#88 Update DockManager to 1.6.0-beta.0
  browser/package.json
  samples/layouts/dock-manager/embedding-frames/package.json
  samples/layouts/dock-manager/hiding-panes/package.json
  samples/layouts/dock-manager/overview/package.json
  samples/layouts/dock-manager/updating-panes/package.json
Labels: status: in-review

#89 Dock Manager styling sample
  browser/package-lock.json
  samples/layouts/dock-manager/styling/.prettierrc
  samples/layouts/dock-manager/styling/ReadMe.md
  samples/layouts/dock-manager/styling/index.html
  samples/layouts/dock-manager/styling/package.json
  samples/layouts/dock-manager/styling/sandbox.config.json
  samples/layouts/dock-manager/styling/src/DockManagerStyles.css
  samples/layouts/dock-manager/styling/src/index.css
  samples/layouts/dock-manager/styling/src/index.ts
  samples/layouts/dock-manager/styling/src/menu-component.ts
  samples/layouts/dock-manager/styling/tsconfig.json
  samples/layouts/dock-manager/styling/webpack.config.js
Labels: area: browser

#87 mdd-21.2-cell-merging
  samples/grids/data-grid/cell-merging/.prettierrc
  samples/grids/data-grid/cell-merging/ReadMe.md
  samples/grids/data-grid/cell-merging/index.html
  samples/grids/data-grid/cell-merging/package.json
  samples/grids/data-grid/cell-merging/sandbox.config.json
  samples/grids/data-grid/cell-merging/src/index.css
  samples/grids/data-grid/cell-merging/src/index.ts
  samples/grids/data-grid/cell-merging/src/odatajs-4.0.0.js
  samples/grids/data-grid/cell-merging/tsconfig.json
  samples/grids/data-grid/cell-merging/webpack.config.js
Labels: status: in-development

#86 mdd-load-save-layout
  samples/grids/data-grid/load-save-layout/.prettierrc
  samples/grids/data-grid/load-save-layout/ReadMe.md
  samples/grids/data-grid/load-save-layout/index.html
  samples/grids/data-grid/load-save-layout/package.json
  samples/grids/data-grid/load-save-layout/sandbox.config.json
  samples/grids/data-grid/load-save-layout/src/DataGridSharedData.ts
  samples/grids/data-grid/load-save-layout/src/index.css
  samples/grids/data-grid/load-save-layout/src/index.ts
  samples/grids/data-grid/load-save-layout/tsconfig.json
  samples/grids/data-grid/load-save-layout/webpack.config.js
Labels: status: in-development
