Repository IgniteUI/igniteui-wc-examples, pull requests merged in 2022-12, with the labels that each got.

#337 Add getting started sample
  browser/public/index.html
  samples/layouts/card/integration/.prettierrc
  samples/layouts/card/integration/ReadMe.md
  samples/layouts/card/integration/index.html
  samples/layouts/card/integration/package.json
  samples/layouts/card/integration/sandbox.config.json
  samples/layouts/card/integration/src/index.css
  samples/layouts/card/integration/src/index.ts
  samples/layouts/card/integration/src/styles.css
  samples/layouts/card/integration/tsconfig.json
  samples/layouts/card/integration/webpack.config.js
Labels: status: in-development

#339 Add sample with pivot and pivot selector.
  browser/tasks/gulp-samples.js
  samples/grids/pivot-grid/binding-data-source/.prettierrc
  samples/grids/pivot-grid/binding-data-source/index.html
  samples/grids/pivot-grid/binding-data-source/package-lock.json
  samples/grids/pivot-grid/binding-data-source/package.json
  samples/grids/pivot-grid/binding-data-source/sandbox.config.json
  samples/grids/pivot-grid/binding-data-source/src/PivotSalesData.ts
  samples/grids/pivot-grid/binding-data-source/src/index.css
  samples/grids/pivot-grid/binding-data-source/src/index.ts
  samples/grids/pivot-grid/binding-data-source/tsconfig.json
  samples/grids/pivot-grid/binding-data-source/tslint.json
  samples/grids/pivot-grid/binding-data-source/webpack.config.js
Labels: status: in-review

#312 feat(stepper): Add stepper samples
  browser/public/index.html
  browser/tasks/gulp-samples.js
  samples/layouts/stepper/linear/.prettierrc
  samples/layouts/stepper/linear/ReadMe.md
  samples/layouts/stepper/linear/index.html
  samples/layouts/stepper/linear/package.json
  samples/layouts/stepper/linear/sandbox.config.json
  samples/layouts/stepper/linear/src/StepperLinear.css
  samples/layouts/stepper/linear/src/index.css
  samples/layouts/stepper/linear/src/index.ts
  samples/layouts/stepper/linear/tsconfig.json
  samples/layouts/stepper/linear/webpack.config.js
  samples/layouts/stepper/orientation/.prettierrc
  samples/layouts/stepper/orientation/ReadMe.md
  samples/layouts/stepper/orientation/index.html
  samples/layouts/stepper/orientation/package.json
  samples/layouts/stepper/orientation/sandbox.config.json
  samples/layouts/stepper/orientation/src/StepperTitlePositionAndOrientation.css
  samples/layouts/stepper/orientation/src/index.css
  samples/layouts/stepper/orientation/src/index.ts
  samples/layouts/stepper/orientation/tsconfig.json
  samples/layouts/stepper/orientation/webpack.config.js
  samples/layouts/stepper/overview/.prettierrc
  samples/layouts/stepper/overview/ReadMe.md
  samples/layouts/stepper/overview/index.html
  samples/layouts/stepper/overview/package.json
  samples/layouts/stepper/overview/sandbox.config.json
  samples/layouts/stepper/overview/src/StepperOverview.css
  samples/layouts/stepper/overview/src/index.css
  samples/layouts/stepper/overview/src/index.ts
  samples/layouts/stepper/overview/tsconfig.json
  samples/layouts/stepper/overview/webpack.config.js
  samples/layouts/stepper/steptypes/.prettierrc
  samples/layouts/stepper/steptypes/ReadMe.md
  samples/layouts/stepper/steptypes/index.html
  samples/layouts/stepper/steptypes/package.json
  samples/layouts/stepper/steptypes/sandbox.config.json
  samples/layouts/stepper/steptypes/src/StepperStepTypes.css
  samples/layouts/stepper/steptypes/src/index.css
  samples/layouts/stepper/steptypes/src/index.ts
  samples/layouts/stepper/steptypes/tsconfig.json
  samples/layouts/stepper/steptypes/webpack.config.js
Labels: status: do-not-merge, status: verified
