Repository IgniteUI/igniteui-wc-examples, pull requests merged in 2022-05, with the labels that each got.

#253 mdd-update-first-marker
  samples/charts/sparkline/markers/index.html
Labels: status: in-review

#258 mdd-add-plot-area-margin
  samples/charts/category-chart/area-chart-multiple-sources/index.html
  samples/charts/category-chart/area-chart-single-source/index.html
  samples/charts/category-chart/area-chart-styling/index.html
  samples/charts/category-chart/line-chart-multiple-sources/index.html
  samples/charts/category-chart/line-chart-single-source/index.html
  samples/charts/category-chart/line-chart-styling/index.html
  samples/charts/category-chart/line-chart-with-animations/index.html
  samples/charts/category-chart/line-chart-with-annotations/index.html
  samples/charts/category-chart/marker-options/index.html
  samples/charts/category-chart/spline-area-multiple-sources/index.html
  samples/charts/category-chart/spline-area-single-source/index.html
  samples/charts/category-chart/spline-multiple-sources/index.html
  samples/charts/category-chart/spline-single-source/index.html
  samples/charts/category-chart/spline-styling/index.html
Labels: status: in-review

#259 mdd-chart-scrollbars
  samples/charts/data-chart/chart-scrollbars/.prettierrc
  samples/charts/data-chart/chart-scrollbars/ReadMe.md
  samples/charts/data-chart/chart-scrollbars/index.html
  samples/charts/data-chart/chart-scrollbars/package.json
  samples/charts/data-chart/chart-scrollbars/sandbox.config.json
  samples/charts/data-chart/chart-scrollbars/src/SampleFinancialData.ts
  samples/charts/data-chart/chart-scrollbars/src/index.css
  samples/charts/data-chart/chart-scrollbars/src/index.ts
  samples/charts/data-chart/chart-scrollbars/tsconfig.json
  samples/charts/data-chart/chart-scrollbars/webpack.config.js
Labels: status: in-review

#257 Add Expansion Panel Samples
  browser/public/index.html
  browser/tasks/gulp-samples.js
  samples/layouts/expansion-panel/component-customization/.prettierrc
  samples/layouts/expansion-panel/component-customization/ReadMe.md
  samples/layouts/expansion-panel/component-customization/index.html
  samples/layouts/expansion-panel/component-customization/package.json
  samples/layouts/expansion-panel/component-customization/sandbox.config.json
  samples/layouts/expansion-panel/component-customization/src/ExpansionPanelCustomization.css
  samples/layouts/expansion-panel/component-customization/src/index.css
  samples/layouts/expansion-panel/component-customization/src/index.ts
  samples/layouts/expansion-panel/component-customization/tsconfig.json
  samples/layouts/expansion-panel/component-customization/webpack.config.js
  samples/layouts/expansion-panel/properties-and-events/.prettierrc
  samples/layouts/expansion-panel/properties-and-events/ReadMe.md
  samples/layouts/expansion-panel/properties-and-events/index.html
  samples/layouts/expansion-panel/properties-and-events/package.json
  samples/layouts/expansion-panel/properties-and-events/sandbox.config.json
  samples/layouts/expansion-panel/properties-and-events/src/ExpansionPanelPropertiesAndEvents.css
  samples/layouts/expansion-panel/properties-and-events/src/index.css
  samples/layouts/expansion-panel/properties-and-events/src/index.ts
  samples/layouts/expansion-panel/properties-and-events/tsconfig.json
  samples/layouts/expansion-panel/properties-and-events/webpack.config.js
  samples/layouts/expansion-panel/styling/.prettierrc
  samples/layouts/expansion-panel/styling/ReadMe.md
  samples/layouts/expansion-panel/styling/index.html
  samples/layouts/expansion-panel/styling/package.json
  samples/layouts/expansion-panel/styling/sandbox.config.json
  samples/layouts/expansion-panel/styling/src/ExpansionPanelStyling.css
  samples/layouts/expansion-panel/styling/src/index.css
  samples/layouts/expansion-panel/styling/src/index.ts
  samples/layouts/expansion-panel/styling/tsconfig.json
  samples/layouts/expansion-panel/styling/webpack.config.js
  samples/layouts/expansion-panel/usage/.prettierrc
  samples/layouts/expansion-panel/usage/ReadMe.md
  samples/layouts/expansion-panel/usage/index.html
  samples/layouts/expansion-panel/usage/package.json
  samples/layouts/expansion-panel/usage/sandbox.config.json
  samples/layouts/expansion-panel/usage/src/ExpansionPanelUsage.css
  samples/layouts/expansion-panel/usage/src/index.css
  samples/layouts/expansion-panel/usage/src/index.ts
  samples/layouts/expansion-panel/usage/tsconfig.json
  samples/layouts/expansion-panel/usage/webpack.config.js
Labels: status: verified

#262 Mdd chart scrollbars
  samples/charts/data-chart/chart-scrollbars/index.html
  samples/charts/data-chart/chart-scrollbars/src/SampleFinancialData.ts
  samples/charts/data-chart/chart-scrollbars/src/index.ts
  samples/charts/financial-chart/scrollbars/.prettierrc
  samples/charts/financial-chart/scrollbars/ReadMe.md
  samples/charts/financial-chart/scrollbars/index.html
  samples/charts/financial-chart/scrollbars/package.json
  samples/charts/financial-chart/scrollbars/sandbox.config.json
  samples/charts/financial-chart/scrollbars/src/StockIndexData.ts
  samples/charts/financial-chart/scrollbars/src/index.css
  samples/charts/financial-chart/scrollbars/src/index.ts
  samples/charts/financial-chart/scrollbars/tsconfig.json
  samples/charts/financial-chart/scrollbars/webpack.config.js
Labels: status: in-review

#264 mdd-pager
  samples/grids/data-grid/pager/.prettierrc
  samples/grids/data-grid/pager/ReadMe.md
  samples/grids/data-grid/pager/index.html
  samples/grids/data-grid/pager/package.json
  samples/grids/data-grid/pager/sandbox.config.json
  samples/grids/data-grid/pager/src/index.css
  samples/grids/data-grid/pager/src/index.ts
  samples/grids/data-grid/pager/tsconfig.json
  samples/grids/data-grid/pager/webpack.config.js
Labels: status: in-review

#266 mdd-localization
  samples/grids/data-grid/localization/.prettierrc
  samples/grids/data-grid/localization/ReadMe.md
  samples/grids/data-grid/localization/index.html
  samples/grids/data-grid/localization/package.json
  samples/grids/data-grid/localization/sandbox.config.json
  samples/grids/data-grid/localization/src/DataGridLocaleJa.ts
  samples/grids/data-grid/localization/src/DataGridSharedData.ts
  samples/grids/data-grid/localization/src/index.css
  samples/grids/data-grid/localization/src/index.ts
  samples/grids/data-grid/localization/tsconfig.json
  samples/grids/data-grid/localization/webpack.config.js
Labels: status: in-review

#269 mdd-update-localization
  samples/grids/data-grid/localization/index.html
  samples/grids/data-grid/localization/src/DataGridLocaleJa.ts
  samples/grids/data-grid/localization/src/DataGridSharedData.ts
  samples/grids/data-grid/localization/src/index.ts
Labels: status: in-review

#219 feat(tree): Add tree samples
  browser/public/index.html
  browser/tasks/gulp-samples.js
  samples/grids/tree/basic-example/.prettierrc
  samples/grids/tree/basic-example/ReadMe.md
  samples/grids/tree/basic-example/index.html
  samples/grids/tree/basic-example/package.json
  samples/grids/tree/basic-example/sandbox.config.json
  samples/grids/tree/basic-example/src/TreeBasic.css
  samples/grids/tree/basic-example/src/index.css
  samples/grids/tree/basic-example/src/index.ts
  samples/grids/tree/basic-example/tsconfig.json
  samples/grids/tree/basic-example/webpack.config.js
  samples/grids/tree/load-on-demand/.prettierrc
  samples/grids/tree/load-on-demand/ReadMe.md
  samples/grids/tree/load-on-demand/index.html
  samples/grids/tree/load-on-demand/package.json
  samples/grids/tree/load-on-demand/sandbox.config.json
  samples/grids/tree/load-on-demand/src/DataService.ts
  samples/grids/tree/load-on-demand/src/LoadOnDemandData.ts
  samples/grids/tree/load-on-demand/src/SvgIcons.ts
  samples/grids/tree/load-on-demand/src/TreeLoadOnDemand.css
  samples/grids/tree/load-on-demand/src/index.css
  samples/grids/tree/load-on-demand/src/index.ts
  samples/grids/tree/load-on-demand/tsconfig.json
  samples/grids/tree/load-on-demand/webpack.config.js
Labels: area: browser, area: samples, status: verified

#267 Rename subTitle slot in the Expansion Panel samples
  samples/layouts/expansion-panel/component-customization/index.html
  samples/layouts/expansion-panel/component-customization/src/ExpansionPanelCustomization.css
  samples/layouts/expansion-panel/properties-and-events/index.html
  samples/layouts/expansion-panel/properties-and-events/src/ExpansionPanelPropertiesAndEvents.css
  samples/layouts/expansion-panel/properties-and-events/src/index.ts
  samples/layouts/expansion-panel/styling/index.html
  samples/layouts/expansion-panel/styling/src/ExpansionPanelStyling.css
  samples/layouts/expansion-panel/usage/index.html
  samples/layouts/expansion-panel/usage/src/ExpansionPanelUsage.css
Labels: area: docs, status: verified
