Repository IgniteUI/igniteui-wc-examples, pull requests merged in 2022-11, with the labels that each got.

#315 feat(select): adding back the samples
  browser/public/index.html
  browser/tasks/gulp-samples.js
  samples/inputs/select/header/index.html
  samples/inputs/select/item/index.html
  samples/inputs/select/styling/index.html
Labels: status: awaiting-test, select

#316 ci(*): create node.js.yml
  .github/workflows/node.js.yml
  .gitignore
  browser/package-lock.json
  browser/package.json
Labels: ci: gh-actions

#317 Mdd more fixes
  samples/grids/data-grid/binding-live-data/src/index.ts
  samples/maps/geo-map/display-heat-imagery/src/heatworker.worker.ts
Labels: status: in-review

#326 chore(*): fixing and reenabling the build
  .github/workflows/node.js.yml
  browser/package-lock.json
  browser/package.json
  browser/public/index.html
  browser/tasks/Transformer.ts
  browser/tasks/gulp-samples.js
Labels: ci: gh-actions
