Repository IgniteUI/igniteui-wc-examples, pull requests merged in 2022-06, with the labels that each got.

#271 Fix-build
  browser/package.json
Labels: status: in-development

#280 Update index.html
  samples/charts/category-chart/high-frequency/index.html
Labels: status: in-review

#282 improve high volume
  samples/charts/category-chart/high-volume/index.html
Labels: status: in-review

#272 row paging
  samples/grids/data-grid/row-paging/index.html
  samples/grids/data-grid/row-paging/package.json
  samples/grids/data-grid/row-paging/src/DataGridSharedData.ts
  samples/grids/data-grid/row-paging/src/index.ts
Labels: status: in-development

#276 Add sample for DockManager with custom buttons
  browser/public/index.html
  samples/layouts/dock-manager/customize-buttons/.prettierrc
  samples/layouts/dock-manager/customize-buttons/ReadMe.md
  samples/layouts/dock-manager/customize-buttons/index.html
  samples/layouts/dock-manager/customize-buttons/package.json
  samples/layouts/dock-manager/customize-buttons/sandbox.config.json
  samples/layouts/dock-manager/customize-buttons/src/DockManagerStyles.css
  samples/layouts/dock-manager/customize-buttons/src/index.css
  samples/layouts/dock-manager/customize-buttons/src/index.ts
  samples/layouts/dock-manager/customize-buttons/tsconfig.json
  samples/layouts/dock-manager/customize-buttons/webpack.config.js
Labels: status: verified

#286 Add missing excel package (Spreadsheet)
  samples/excel/spreadsheet/activation/package.json
  samples/excel/spreadsheet/clipboard/package.json
  samples/excel/spreadsheet/commands/package.json
  samples/excel/spreadsheet/conditional-formatting/package.json
  samples/excel/spreadsheet/config-options/package.json
  samples/excel/spreadsheet/filter-dialog/package.json
  samples/excel/spreadsheet/format-dialog/package.json
  samples/excel/spreadsheet/hyperlinks/package.json
  samples/excel/spreadsheet/sort-dialog/package.json
Labels: status: in-review

#287 Add layouts package
  samples/excel/excel-library/operations-on-workbooks/package.json
  samples/excel/excel-library/working-with-charts/package.json
  samples/excel/excel-library/working-with-sparklines/package.json
Labels: status: in-review

#288 Define icon component in Expansion Panel and Tree samples
  samples/grids/tree/basic-example/src/index.ts
  samples/layouts/expansion-panel/component-customization/src/index.ts
  samples/layouts/expansion-panel/properties-and-events/src/index.ts
  samples/layouts/expansion-panel/styling/src/index.ts
  samples/layouts/expansion-panel/usage/src/index.ts
Labels: area: samples
