Repository IgniteUI/igniteui-wc-examples, pull requests merged in 2023-10, with the labels that each got.

#416 Add more complex custom group by sample for wc grid.
  samples/grids/grid/groupby-custom/index.html
  samples/grids/grid/groupby-custom/src/index.ts
Labels: status: do-not-merge, status: verified, status: waiting for xplat PR

#421 Update clipboard operations sample.
  samples/grids/grid/clipboard-operations/index.html
  samples/grids/grid/clipboard-operations/src/index.ts
Labels: status: verified

#494 Combo: Show value usage
  samples/inputs/combo/overview/index.html
Labels: status: verified, control: combo
