Repository IgniteUI/igniteui-wc-examples, pull requests merged in 2023-01, with the labels that each got.

#349 Update mapServerUri
  samples/layouts/dock-manager/updating-panes/src/index.ts
Labels: area: samples, status: verified

#347 fix(stepper): samples styling and validation issues
  samples/layouts/stepper/linear/src/index.ts
  samples/layouts/stepper/overview/src/StepperOverview.css
  samples/layouts/stepper/overview/src/index.ts
Labels: status: in-development, stepper

#343 Add Pivot Remote sample
  samples/grids/pivot-grid/remote/.prettierrc
  samples/grids/pivot-grid/remote/index.html
  samples/grids/pivot-grid/remote/package-lock.json
  samples/grids/pivot-grid/remote/package.json
  samples/grids/pivot-grid/remote/sandbox.config.json
  samples/grids/pivot-grid/remote/src/PivotNoopData.ts
  samples/grids/pivot-grid/remote/src/index.css
  samples/grids/pivot-grid/remote/src/index.ts
  samples/grids/pivot-grid/remote/tsconfig.json
  samples/grids/pivot-grid/remote/tsling.json
  samples/grids/pivot-grid/remote/webpack.config.js
Labels: status: do-not-merge

#361 Fix templated icons size
  package.json
  samples/layouts/dock-manager/add-content-runtime/package.json
  samples/layouts/dock-manager/customize-buttons/index.html
  samples/layouts/dock-manager/customize-buttons/package.json
  samples/layouts/dock-manager/embedding-frames/package.json
  samples/layouts/dock-manager/hiding-panes/package.json
  samples/layouts/dock-manager/overview/package.json
  samples/layouts/dock-manager/styling/package.json
  samples/layouts/dock-manager/updating-panes/package.json
Labels: status: awaiting-test

#352 fix(stepper): Remove an unnecessary backslash from the mask of a masked input
  samples/layouts/stepper/overview/index.html
Labels: status: awaiting-test, stepper

#364 chore(ci): reenabling CI
  .github/workflows/node.js.yml
Labels: ci: gh-actions

#367 mdd-remove-batchediting
  samples/grids/grid/action-strip/index.html
  samples/grids/grid/data-batch-editing-actions/index.html
  samples/grids/grid/data-paste-options/index.html
  samples/grids/grid/data-validator-service-cross-field/index.html
  samples/grids/grid/data-validator-service-extended/index.html
  samples/grids/grid/data-validator-service/index.html
  samples/grids/grid/multi-row-layout-options/index.html
Labels: status: in-review
