Repository IgniteUI/igniteui-wc-examples, pull requests merged in 2023-06, with the labels that each got.

#458 Add custom context menu sample.
  samples/grids/grid/custom-context-menu/.prettierrc
  samples/grids/grid/custom-context-menu/ReadMe.md
  samples/grids/grid/custom-context-menu/index.html
  samples/grids/grid/custom-context-menu/package.json
  samples/grids/grid/custom-context-menu/sandbox.config.json
  samples/grids/grid/custom-context-menu/src/NwindData.ts
  samples/grids/grid/custom-context-menu/src/index.css
  samples/grids/grid/custom-context-menu/src/index.ts
  samples/grids/grid/custom-context-menu/tsconfig.json
  samples/grids/grid/custom-context-menu/tslint.json
  samples/grids/grid/custom-context-menu/webpack.config.js
Labels: status: verified

#460 Live-data Update sample for wc
  samples/grids/grid/finjs/.prettierrc
  samples/grids/grid/finjs/ReadMe.md
  samples/grids/grid/finjs/index.html
  samples/grids/grid/finjs/package.json
  samples/grids/grid/finjs/sandbox.config.json
  samples/grids/grid/finjs/src/FinancialData.ts
  samples/grids/grid/finjs/src/index.css
  samples/grids/grid/finjs/src/index.ts
  samples/grids/grid/finjs/tsconfig.json
  samples/grids/grid/finjs/tslint.json
  samples/grids/grid/finjs/webpack.config.js
Labels: status: verified

#491 mdd-update-packages-toolbar
  samples/charts/toolbar/actions-built-in-category-chart/package.json
  samples/charts/toolbar/actions-built-in-data-chart/package.json
  samples/charts/toolbar/layout-actions-for-data-chart/package.json
  samples/charts/toolbar/layout-in-vertical-orientation/package.json
  samples/charts/toolbar/theming/package.json
Labels: status: in-review

#495 Add flat grid infinite scroll sample
  browser/public/index.html
  package-lock.json
  samples/charts/sparkline/display-area/index.html
  samples/grids/grid/infinite-scroll/.prettierrc
  samples/grids/grid/infinite-scroll/ReadMe.md
  samples/grids/grid/infinite-scroll/index.html
  samples/grids/grid/infinite-scroll/package.json
  samples/grids/grid/infinite-scroll/sandbox.config.json
  samples/grids/grid/infinite-scroll/src/NwindData.ts
  samples/grids/grid/infinite-scroll/src/NwindService.ts
  samples/grids/grid/infinite-scroll/src/index.css
  samples/grids/grid/infinite-scroll/src/index.ts
  samples/grids/grid/infinite-scroll/tsconfig.json
  samples/grids/grid/infinite-scroll/tslint.json
  samples/grids/grid/infinite-scroll/webpack.config.js
  samples/inputs/dropdown/position/src/DropDownPositionStyles.css
  samples/inputs/dropdown/styling/src/DropDownStyling.css
  samples/inputs/slider/constraints/src/SliderConstraintsStyle.css
  samples/inputs/slider/disabled/src/SliderDisabledStyle.css
  samples/inputs/slider/discrete/src/SliderDiscreteStyle.css
  samples/inputs/slider/labels/src/SliderLabelsStyle.css
  samples/inputs/slider/overview/src/SliderOverviewStyle.css
  samples/inputs/slider/styling/src/SliderStyling.css
  samples/inputs/slider/tick-labels/src/SliderTickLabelsStyle.css
  samples/inputs/slider/ticks/src/SliderTicksStyle.css
  samples/inputs/slider/value-format/src/SliderValueFormatStyle.css
  samples/inputs/slider/value/src/SliderValueStyle.css
Labels: status: in-development
