Repository IgniteUI/igniteui-wc-examples, pull requests merged in 2024-04, with the labels that each got.

#701 mdd-highlight-needle-gauges
  samples/gauges/bullet-graph/highlight-needle/.prettierrc
  samples/gauges/bullet-graph/highlight-needle/ReadMe.md
  samples/gauges/bullet-graph/highlight-needle/index.html
  samples/gauges/bullet-graph/highlight-needle/package.json
  samples/gauges/bullet-graph/highlight-needle/sandbox.config.json
  samples/gauges/bullet-graph/highlight-needle/src/index.css
  samples/gauges/bullet-graph/highlight-needle/src/index.ts
  samples/gauges/bullet-graph/highlight-needle/tsconfig.json
  samples/gauges/bullet-graph/highlight-needle/webpack.config.js
  samples/gauges/linear-gauge/highlight-needle/.prettierrc
  samples/gauges/linear-gauge/highlight-needle/ReadMe.md
  samples/gauges/linear-gauge/highlight-needle/index.html
  samples/gauges/linear-gauge/highlight-needle/package.json
  samples/gauges/linear-gauge/highlight-needle/sandbox.config.json
  samples/gauges/linear-gauge/highlight-needle/src/index.css
  samples/gauges/linear-gauge/highlight-needle/src/index.ts
  samples/gauges/linear-gauge/highlight-needle/tsconfig.json
  samples/gauges/linear-gauge/highlight-needle/webpack.config.js
  samples/gauges/radial-gauge/highlight-needle/.prettierrc
  samples/gauges/radial-gauge/highlight-needle/ReadMe.md
  samples/gauges/radial-gauge/highlight-needle/index.html
  samples/gauges/radial-gauge/highlight-needle/package.json
  samples/gauges/radial-gauge/highlight-needle/sandbox.config.json
  samples/gauges/radial-gauge/highlight-needle/src/index.css
  samples/gauges/radial-gauge/highlight-needle/src/index.ts
  samples/gauges/radial-gauge/highlight-needle/tsconfig.json
  samples/gauges/radial-gauge/highlight-needle/webpack.config.js
Labels: status: in-review

#694 Update stepper demos from igc-form to native form
  samples/layouts/stepper/animations/index.html
  samples/layouts/stepper/linear/index.html
  samples/layouts/stepper/linear/src/index.ts
  samples/layouts/stepper/overview/index.html
  samples/layouts/stepper/overview/src/index.ts
Labels: status: verified

#705 fix(button-group): register icons from text and set correct size
  samples/inputs/button-group/overview/src/index.ts
  samples/inputs/button-group/selection/index.html
  samples/inputs/button-group/selection/src/index.ts
  samples/inputs/button-group/size/src/index.css
  samples/inputs/button-group/size/src/index.ts
Labels: control: button-group

#683 Add hGrid data virtualization sample
  browser/public/index.html
  samples/grids/hierarchical-grid/data-performance-virtualization/.prettierrc
  samples/grids/hierarchical-grid/data-performance-virtualization/ReadMe.md
  samples/grids/hierarchical-grid/data-performance-virtualization/index.html
  samples/grids/hierarchical-grid/data-performance-virtualization/package.json
  samples/grids/hierarchical-grid/data-performance-virtualization/sandbox.config.json
  samples/grids/hierarchical-grid/data-performance-virtualization/src/RemoteService.ts
  samples/grids/hierarchical-grid/data-performance-virtualization/src/data.ts
  samples/grids/hierarchical-grid/data-performance-virtualization/src/index.css
  samples/grids/hierarchical-grid/data-performance-virtualization/src/index.ts
  samples/grids/hierarchical-grid/data-performance-virtualization/tsconfig.json
  samples/grids/hierarchical-grid/data-performance-virtualization/tslint.json
  samples/grids/hierarchical-grid/data-performance-virtualization/webpack.config.js
Labels: status: verified

#725 refactor(hGrid-lod): use Indigo Design Northwind data service
  samples/grids/hierarchical-grid/data-performance-virtualization/index.html
  samples/grids/hierarchical-grid/data-performance-virtualization/src/RemoteService.ts
  samples/grids/hierarchical-grid/data-performance-virtualization/src/data.ts
  samples/grids/hierarchical-grid/data-performance-virtualization/src/index.ts
Labels: status: verified

#681 Add hGrid custom toolbar samples
  browser/public/index.html
  samples/grids/hierarchical-grid/data-exporting-indicator/.prettierrc
  samples/grids/hierarchical-grid/data-exporting-indicator/ReadMe.md
  samples/grids/hierarchical-grid/data-exporting-indicator/index.html
  samples/grids/hierarchical-grid/data-exporting-indicator/package.json
  samples/grids/hierarchical-grid/data-exporting-indicator/sandbox.config.json
  samples/grids/hierarchical-grid/data-exporting-indicator/src/SingersData.ts
  samples/grids/hierarchical-grid/data-exporting-indicator/src/index.css
  samples/grids/hierarchical-grid/data-exporting-indicator/src/index.ts
  samples/grids/hierarchical-grid/data-exporting-indicator/tsconfig.json
  samples/grids/hierarchical-grid/data-exporting-indicator/tslint.json
  samples/grids/hierarchical-grid/data-exporting-indicator/webpack.config.js
  samples/grids/hierarchical-grid/toolbar-sample-4/.prettierrc
  samples/grids/hierarchical-grid/toolbar-sample-4/ReadMe.md
  samples/grids/hierarchical-grid/toolbar-sample-4/index.html
  samples/grids/hierarchical-grid/toolbar-sample-4/package.json
  samples/grids/hierarchical-grid/toolbar-sample-4/sandbox.config.json
  samples/grids/hierarchical-grid/toolbar-sample-4/src/SingersData.ts
  samples/grids/hierarchical-grid/toolbar-sample-4/src/index.css
  samples/grids/hierarchical-grid/toolbar-sample-4/src/index.ts
  samples/grids/hierarchical-grid/toolbar-sample-4/tsconfig.json
  samples/grids/hierarchical-grid/toolbar-sample-4/tslint.json
  samples/grids/hierarchical-grid/toolbar-sample-4/webpack.config.js
Labels: status: verified
