Repository IgniteUI/igniteui-wc-examples, pull requests merged in 2024-09, with the labels that each got.

#823 Add old samples for now deprecated XDatePicker
  samples/editors/x-date-picker/date-limits/.prettierrc
  samples/editors/x-date-picker/date-limits/ReadMe.md
  samples/editors/x-date-picker/date-limits/index.html
  samples/editors/x-date-picker/date-limits/package.json
  samples/editors/x-date-picker/date-limits/sandbox.config.json
  samples/editors/x-date-picker/date-limits/src/index.css
  samples/editors/x-date-picker/date-limits/src/index.ts
  samples/editors/x-date-picker/date-limits/tsconfig.json
  samples/editors/x-date-picker/date-limits/webpack.config.js
  samples/editors/x-date-picker/editing/.prettierrc
  samples/editors/x-date-picker/editing/ReadMe.md
  samples/editors/x-date-picker/editing/index.html
  samples/editors/x-date-picker/editing/package.json
  samples/editors/x-date-picker/editing/sandbox.config.json
  samples/editors/x-date-picker/editing/src/index.css
  samples/editors/x-date-picker/editing/src/index.ts
  samples/editors/x-date-picker/editing/tsconfig.json
  samples/editors/x-date-picker/editing/webpack.config.js
  samples/editors/x-date-picker/format/.prettierrc
  samples/editors/x-date-picker/format/ReadMe.md
  samples/editors/x-date-picker/format/index.html
  samples/editors/x-date-picker/format/package.json
  samples/editors/x-date-picker/format/sandbox.config.json
  samples/editors/x-date-picker/format/src/index.css
  samples/editors/x-date-picker/format/src/index.ts
  samples/editors/x-date-picker/format/tsconfig.json
  samples/editors/x-date-picker/format/webpack.config.js
  samples/editors/x-date-picker/overview/.prettierrc
  samples/editors/x-date-picker/overview/ReadMe.md
  samples/editors/x-date-picker/overview/index.html
  samples/editors/x-date-picker/overview/package.json
  samples/editors/x-date-picker/overview/sandbox.config.json
  samples/editors/x-date-picker/overview/src/index.css
  samples/editors/x-date-picker/overview/src/index.ts
  samples/editors/x-date-picker/overview/tsconfig.json
  samples/editors/x-date-picker/overview/webpack.config.js
  samples/editors/x-date-picker/range/.prettierrc
  samples/editors/x-date-picker/range/ReadMe.md
  samples/editors/x-date-picker/range/index.html
  samples/editors/x-date-picker/range/package.json
  samples/editors/x-date-picker/range/sandbox.config.json
  samples/editors/x-date-picker/range/src/index.css
  samples/editors/x-date-picker/range/src/index.ts
  samples/editors/x-date-picker/range/tsconfig.json
  samples/editors/x-date-picker/range/webpack.config.js
  samples/scheduling/date-picker/dialog-mode/.prettierrc
  samples/scheduling/date-picker/dialog-mode/ReadMe.md
  samples/scheduling/date-picker/dialog-mode/index.html
  samples/scheduling/date-picker/dialog-mode/package.json
  samples/scheduling/date-picker/dialog-mode/sandbox.config.json
  samples/scheduling/date-picker/dialog-mode/src/index.css
  samples/scheduling/date-picker/dialog-mode/src/index.ts
  samples/scheduling/date-picker/dialog-mode/tsconfig.json
  samples/scheduling/date-picker/dialog-mode/webpack.config.js
Labels: status: verified, control: date-picker

#811 Add grid custom icons change sample.
  samples/grids/grid/change-icons-custom/.prettierrc
  samples/grids/grid/change-icons-custom/ReadMe.md
  samples/grids/grid/change-icons-custom/index.html
  samples/grids/grid/change-icons-custom/package.json
  samples/grids/grid/change-icons-custom/sandbox.config.json
  samples/grids/grid/change-icons-custom/src/NwindData.ts
  samples/grids/grid/change-icons-custom/src/icons.ts
  samples/grids/grid/change-icons-custom/src/index.css
  samples/grids/grid/change-icons-custom/src/index.ts
  samples/grids/grid/change-icons-custom/tsconfig.json
  samples/grids/grid/change-icons-custom/tslint.json
  samples/grids/grid/change-icons-custom/webpack.config.js
Labels: status: verified

#743 added grid and hgrid remote paging samples
  browser/public/index.html
  samples/grids/grid/remote-paging-grid/.prettierrc
  samples/grids/grid/remote-paging-grid/ReadMe.md
  samples/grids/grid/remote-paging-grid/index.html
  samples/grids/grid/remote-paging-grid/package.json
  samples/grids/grid/remote-paging-grid/sandbox.config.json
  samples/grids/grid/remote-paging-grid/src/RemotePagingService.ts
  samples/grids/grid/remote-paging-grid/src/index.css
  samples/grids/grid/remote-paging-grid/src/index.ts
  samples/grids/grid/remote-paging-grid/tsconfig.json
  samples/grids/grid/remote-paging-grid/tslint.json
  samples/grids/grid/remote-paging-grid/webpack.config.js
  samples/grids/hierarchical-grid/remote-paging-sample/.prettierrc
  samples/grids/hierarchical-grid/remote-paging-sample/ReadMe.md
  samples/grids/hierarchical-grid/remote-paging-sample/index.html
  samples/grids/hierarchical-grid/remote-paging-sample/package.json
  samples/grids/hierarchical-grid/remote-paging-sample/sandbox.config.json
  samples/grids/hierarchical-grid/remote-paging-sample/src/RemoteService.ts
  samples/grids/hierarchical-grid/remote-paging-sample/src/index.css
  samples/grids/hierarchical-grid/remote-paging-sample/src/index.ts
  samples/grids/hierarchical-grid/remote-paging-sample/tsconfig.json
  samples/grids/hierarchical-grid/remote-paging-sample/tslint.json
  samples/grids/hierarchical-grid/remote-paging-sample/webpack.config.js
Labels: status: verified

#808 Update index.html
  samples/gauges/radial-gauge/labels/index.html
Labels: status: in-review

#787 docs(grid): new implementation of excel style editing
  samples/grids/grid/editing-excel-style-custom/.prettierrc
  samples/grids/grid/editing-excel-style-custom/ReadMe.md
  samples/grids/grid/editing-excel-style-custom/index.html
  samples/grids/grid/editing-excel-style-custom/package.json
  samples/grids/grid/editing-excel-style-custom/sandbox.config.json
  samples/grids/grid/editing-excel-style-custom/src/NwindData.ts
  samples/grids/grid/editing-excel-style-custom/src/index.css
  samples/grids/grid/editing-excel-style-custom/src/index.ts
  samples/grids/grid/editing-excel-style-custom/tsconfig.json
  samples/grids/grid/editing-excel-style-custom/tslint.json
  samples/grids/grid/editing-excel-style-custom/webpack.config.js
Labels: status: verified

#833 Fix context sample event arg cell id getter changed in new version.
  samples/grids/grid/custom-context-menu/src/index.ts
Labels: status: verified

#835 chore(*): Get dom elements on demand after load.
  samples/grids/pivot-grid/data-persistence-noop/src/index.ts
  samples/grids/pivot-grid/state-persistence-main/src/index.ts
Labels: status: verified
